### ISSUE TITLE
Unsupported language selector dropdown

### ISSUE THREAD

**Issue by andreylds** [translationexchange/tml-rails#1]
Hi, I got error after use 
<%= tml_language_selector_tag(:dropdown, {:style => "margin-top:15px", :language => :english}) %>
- Unsupported language selector dropdown

please help.

**Comment by berk** [comment]
Andrey, somehow we used to call it "list" instead of "dropdown" on the rails side. But i fixed it now. If you get the latest gem, you can use either "list" or "dropdown" now.

<%= tml_language_selector_tag(:dropdown, {:style => "margin-top:15px", :language => :english}) %>

This should work now.

Let me know if you need us to add any other language selector styles. It's fairly easy to add any number of them and you can obviously build your own.

**Comment by andreylds** [comment]
@berk Thank you very much.

**Comment by naveenputta** [comment]
Hi @berk , When I clicks on the drop down to change the language, in the back it is sending the request and getting the response. But my view is not updating with the selected language. Can you please help me on that.
