### ISSUE TITLE
Automatic form labels not generated properly when using tml as i18n bakend

### ISSUE THREAD

**Issue by thatguysimon** [translationexchange/tml-rails#3]
Hi there,
I'm having an issue while using **tml as i18n backend**.
When using rails' feature for automatically generating labels using the model's attributes:

``` ruby
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
```

Instead of generating the text "Email", the text generated is 

```
User.email
*textbox here*
```

Commenting out "I18n.backend = I18n::Backend::Tml.new" makes this feature work properly again.

Thanks for your help.
Simon.

**Comment by berk** [comment]
Thank you for reporting. It is now fixed in gem 5.1.2. You can see the sample app here:

https://github.com/translationexchange/tml-rails-samples-welp/blob/master/rails_4.2_i18n/app/views/test/forms.html.erb

One of the fields comes from i18n file and one uses a default name derived from the key:

https://github.com/translationexchange/tml-rails-samples-welp/blob/master/rails_4.2_i18n/config/locales/en.yml#L27
